services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: urlshortener
      POSTGRES_PASSWORD: myPassword
      POSTGRES_DB: urlshortener
    volumes:
      - urlshortener_pgdata:/var/lib/postgresql/data 

volumes:
  urlshortener_pgdata: